class SockSyncErrors:
    ERROR_INVALID_FUNC = 1
    ERROR_INVALID_TYPE = 2
    ERROR_INVALID_NAME = 3
    ERROR_MISSING_FIELD = 4
    ERROR_BAD_INDEX = 5
    ERROR_BAD_ID = 6
    ERROR_INVALID_JSON = 7
    ERROR_OTHER = 8
